import { useNavigate, useParams } from 'react-router';
import { Button } from '../components/ui/button';
import { Card } from '../components/ui/card';
import { Badge } from '../components/ui/badge';
import { Separator } from '../components/ui/separator';
import { ArrowLeft, FileText, TrendingUp, DollarSign, Target, Download, Share2, CheckCircle } from 'lucide-react';
import { mockStartups, mockInvestorBriefs } from '../lib/mockData';
import { toast } from "sonner";

export function InvestorBrief() {
  const navigate = useNavigate();
  const { startupId } = useParams();
  const startup = mockStartups.find(s => s.id === startupId);
  const brief = startupId ? mockInvestorBriefs[startupId] : null;

  if (!startup || !brief) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <Card className="p-8 text-center">
          <h2 className="mb-2">Brief Not Found</h2>
          <p className="text-gray-600 mb-4">This startup doesn't have an investor brief yet.</p>
          <Button onClick={() => navigate('/dashboard')}>Back to Dashboard</Button>
        </Card>
      </div>
    );
  }

  const handleDownload = () => {
    toast.success('AI Brief downloaded as PDF');
  };

  const handleShare = () => {
    toast.success('Brief link copied to clipboard');
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="bg-white border-b">
        <div className="container mx-auto px-4 py-4">
          <Button variant="ghost" onClick={() => navigate('/dashboard')} className="gap-2 mb-4">
            <ArrowLeft className="w-4 h-4" />
            Back to Dashboard
          </Button>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <FileText className="w-8 h-8 text-blue-600" />
              <div>
                <h1>AI-Generated Investor Brief</h1>
                <p className="text-gray-600">Investment intelligence report</p>
              </div>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" onClick={handleShare} className="gap-2">
                <Share2 className="w-4 h-4" />
                Share
              </Button>
              <Button onClick={handleDownload} className="gap-2">
                <Download className="w-4 h-4" />
                Download PDF
              </Button>
            </div>
          </div>
        </div>
      </div>

      <div className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          {/* Header Card */}
          <Card className="p-8 mb-6 bg-gradient-to-r from-blue-600 to-purple-600 text-white">
            <div className="flex justify-between items-start mb-4">
              <div>
                <Badge className="bg-white/20 text-white border-white/30 mb-3">
                  Investment Opportunity
                </Badge>
                <h2 className="text-white text-3xl mb-2">{startup.name}</h2>
                <p className="text-blue-100 text-lg">{startup.description}</p>
              </div>
            </div>
            <div className="grid grid-cols-4 gap-4 mt-6">
              <div>
                <div className="text-blue-100 text-sm mb-1">Industry</div>
                <div className="font-semibold">{startup.industry}</div>
              </div>
              <div>
                <div className="text-blue-100 text-sm mb-1">Stage</div>
                <div className="font-semibold capitalize">{startup.stage.replace('-', ' ')}</div>
              </div>
              <div>
                <div className="text-blue-100 text-sm mb-1">Seeking</div>
                <div className="font-semibold">${(startup.budgetNeeded / 1000).toFixed(0)}K</div>
              </div>
              <div>
                <div className="text-blue-100 text-sm mb-1">AI Score</div>
                <div className="font-semibold">{startup.aiScore}/100</div>
              </div>
            </div>
          </Card>

          {/* Generated Info */}
          <div className="flex justify-between items-center mb-6 text-sm text-gray-600">
            <div className="flex items-center gap-2">
              <CheckCircle className="w-4 h-4 text-green-600" />
              Generated by AI on {brief.generatedAt}
            </div>
            <div>
              Last updated: {brief.generatedAt}
            </div>
          </div>

          {/* Executive Summary */}
          <Card className="p-6 mb-6">
            <div className="flex items-center gap-2 mb-4">
              <FileText className="w-5 h-5 text-blue-600" />
              <h3>Executive Summary</h3>
            </div>
            <p className="text-gray-700 leading-relaxed">{brief.summary}</p>
          </Card>

          {/* Market Analysis */}
          <Card className="p-6 mb-6">
            <div className="flex items-center gap-2 mb-4">
              <TrendingUp className="w-5 h-5 text-green-600" />
              <h3>Market Analysis & Opportunity</h3>
            </div>
            <p className="text-gray-700 leading-relaxed mb-4">{brief.marketAnalysis}</p>
            {startup.marketPotential && (
              <div className="bg-green-50 border border-green-200 rounded-lg p-4">
                <div className="flex items-center gap-2">
                  <div className="text-sm font-medium text-green-900">Market Potential:</div>
                  <Badge className="bg-green-600 text-white">
                    {startup.marketPotential.toUpperCase().replace('-', ' ')}
                  </Badge>
                </div>
              </div>
            )}
          </Card>

          {/* Funding Needs */}
          <Card className="p-6 mb-6">
            <div className="flex items-center gap-2 mb-4">
              <DollarSign className="w-5 h-5 text-purple-600" />
              <h3>Funding Needs & Allocation</h3>
            </div>
            <p className="text-gray-700 leading-relaxed mb-4">{brief.fundingNeeds}</p>
            <Separator className="my-4" />
            <div>
              <div className="font-medium mb-2">Budget Breakdown</div>
              <p className="text-gray-700">{startup.budgetBreakdown}</p>
            </div>
          </Card>

          {/* Compatibility Insights */}
          <Card className="p-6 mb-6">
            <div className="flex items-center gap-2 mb-4">
              <Target className="w-5 h-5 text-orange-600" />
              <h3>Investment Compatibility Insights</h3>
            </div>
            <div className="space-y-3">
              {brief.compatibilityInsights.map((insight, index) => (
                <div key={index} className="flex gap-3 items-start">
                  <CheckCircle className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
                  <p className="text-gray-700">{insight}</p>
                </div>
              ))}
            </div>
          </Card>

          {/* Recommended Actions */}
          <Card className="p-6 bg-blue-50 border-blue-200">
            <h3 className="mb-4">Next Steps</h3>
            <div className="space-y-3">
              <Button 
                onClick={() => navigate('/funder-matching')} 
                className="w-full justify-start gap-2"
              >
                <TrendingUp className="w-4 h-4" />
                View Matched Funders
              </Button>
              <Button 
                onClick={() => navigate(`/co-investment/${startup.id}`)} 
                variant="outline"
                className="w-full justify-start gap-2"
              >
                <Target className="w-4 h-4" />
                Explore Co-Investment Opportunities
              </Button>
            </div>
          </Card>

          {/* AI Disclaimer */}
          <div className="mt-6 text-sm text-gray-500 text-center">
            This brief was generated by AI based on startup information and market data. 
            All insights should be verified independently before making investment decisions.
          </div>
        </div>
      </div>
    </div>
  );
}
