import { Startup, Mentor, Funder, InvestorBrief } from '../types';

export const mockStartups: Startup[] = [
  {
    id: '1',
    name: 'EcoTrack',
    description: 'AI-powered carbon footprint tracking and reduction platform for SMEs',
    industry: 'CleanTech',
    stage: 'mvp',
    budgetNeeded: 250000,
    budgetBreakdown: 'Product development: $100k, Marketing: $80k, Operations: $70k',
    status: 'ready',
    submittedAt: '2026-04-15',
    mentorId: '1',
    aiScore: 87,
    marketPotential: 'high',
  },
  {
    id: '2',
    name: 'HealthAI',
    description: 'Personalized nutrition and wellness platform using machine learning',
    industry: 'HealthTech',
    stage: 'idea',
    budgetNeeded: 150000,
    budgetBreakdown: 'Research & Development: $90k, Team: $40k, Infrastructure: $20k',
    status: 'mentoring',
    submittedAt: '2026-05-01',
    mentorId: '2',
    aiScore: 72,
    marketPotential: 'medium',
  },
  {
    id: '3',
    name: 'EduConnect',
    description: 'Peer-to-peer learning marketplace connecting students globally',
    industry: 'EdTech',
    stage: 'early-revenue',
    budgetNeeded: 500000,
    budgetBreakdown: 'Platform scaling: $200k, Marketing: $150k, Content: $100k, Operations: $50k',
    status: 'ready',
    submittedAt: '2026-03-20',
    mentorId: '3',
    aiScore: 91,
    marketPotential: 'very-high',
  },
];

export const mockMentors: Mentor[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    expertise: ['Product Development', 'Go-to-Market', 'Sustainability'],
    industries: ['CleanTech', 'GreenTech', 'Energy'],
    yearsExperience: 15,
    bio: 'Former VP of Product at Tesla. Helped 20+ cleantech startups scale.',
    startupsHelped: 23,
  },
  {
    id: '2',
    name: 'Dr. James Wilson',
    expertise: ['Healthcare', 'AI/ML', 'Regulatory Compliance'],
    industries: ['HealthTech', 'BioTech', 'MedTech'],
    yearsExperience: 12,
    bio: 'Healthcare AI researcher and 3x founder. Expert in FDA approval processes.',
    startupsHelped: 18,
  },
  {
    id: '3',
    name: 'Maria Rodriguez',
    expertise: ['EdTech', 'User Acquisition', 'Product-Market Fit'],
    industries: ['EdTech', 'E-Learning', 'SaaS'],
    yearsExperience: 10,
    bio: 'Built and sold 2 EdTech companies. Specializes in early-stage growth.',
    startupsHelped: 31,
  },
  {
    id: '4',
    name: 'Alex Kumar',
    expertise: ['Fintech', 'Blockchain', 'Regulatory Strategy'],
    industries: ['FinTech', 'Crypto', 'Banking'],
    yearsExperience: 14,
    bio: 'Former Goldman Sachs exec. Now mentoring next-gen fintech founders.',
    startupsHelped: 15,
  },
];

export const mockFunders: Funder[] = [
  {
    id: '1',
    name: 'GreenVentures Capital',
    type: 'vc',
    industries: ['CleanTech', 'GreenTech', 'Sustainability'],
    stages: ['mvp', 'early-revenue', 'growth'],
    minInvestment: 100000,
    maxInvestment: 2000000,
    bio: 'Leading climate tech VC with $500M AUM. Focused on scalable environmental solutions.',
    successfulInvestments: 47,
  },
  {
    id: '2',
    name: 'HealthFirst Angels',
    type: 'angel',
    industries: ['HealthTech', 'BioTech', 'Wellness'],
    stages: ['idea', 'mvp', 'early-revenue'],
    minInvestment: 50000,
    maxInvestment: 500000,
    bio: 'Angel network of 30+ healthcare executives and physicians.',
    successfulInvestments: 28,
  },
  {
    id: '3',
    name: 'EduFund Ventures',
    type: 'vc',
    industries: ['EdTech', 'E-Learning', 'HRTech'],
    stages: ['early-revenue', 'growth'],
    minInvestment: 250000,
    maxInvestment: 5000000,
    bio: 'EdTech-focused VC backing innovative learning platforms globally.',
    successfulInvestments: 62,
  },
  {
    id: '4',
    name: 'TechCorp Innovation Fund',
    type: 'corporate',
    industries: ['AI', 'SaaS', 'Enterprise'],
    stages: ['mvp', 'early-revenue', 'growth'],
    minInvestment: 200000,
    maxInvestment: 3000000,
    bio: 'Corporate venture arm investing in B2B technology startups.',
    successfulInvestments: 35,
  },
  {
    id: '5',
    name: 'Impact Seed Fund',
    type: 'vc',
    industries: ['CleanTech', 'HealthTech', 'EdTech', 'SocialImpact'],
    stages: ['idea', 'mvp'],
    minInvestment: 75000,
    maxInvestment: 300000,
    bio: 'Early-stage fund supporting mission-driven startups with social impact.',
    successfulInvestments: 41,
  },
];

export const mockInvestorBriefs: Record<string, InvestorBrief> = {
  '1': {
    startupId: '1',
    summary: 'EcoTrack addresses the growing SME carbon compliance market with an AI-powered solution. The platform automates carbon tracking, provides actionable reduction insights, and generates compliance reports. With an MVP validated by 15 pilot customers and 40% MoM growth, EcoTrack is positioned to capture market share in a $12B addressable market.',
    marketAnalysis: 'The carbon management software market is experiencing 23% CAGR, driven by regulatory pressures (EU CSRD, SEC climate rules) and corporate sustainability commitments. SMEs represent 90% of businesses but lack affordable solutions. EcoTrack\'s competitive advantage lies in its automated data integration and industry-specific benchmarking.',
    fundingNeeds: 'Seeking $250K to accelerate product development, expand sales team, and scale customer acquisition. Funds will enable platform enhancements, integration partnerships, and market expansion to 3 additional verticals within 12 months.',
    compatibilityInsights: [
      'Strong alignment with ESG-focused investors',
      'Proven traction with measurable KPIs',
      'Experienced founding team with domain expertise',
      'Clear path to profitability within 18 months',
      'Strategic partnerships with industry associations',
    ],
    recommendedFunders: ['1', '5'],
    generatedAt: '2026-05-10',
  },
  '3': {
    startupId: '3',
    summary: 'EduConnect operates a peer-to-peer learning marketplace connecting 50,000+ students across 30 countries. The platform enables knowledge exchange through live sessions, recorded content, and community forums. Current MRR of $18K with 65% gross margins demonstrates strong unit economics and scalability potential.',
    marketAnalysis: 'The global online education market is projected to reach $350B by 2028. Peer learning models show 40% higher engagement than traditional e-learning. EduConnect differentiates through quality curation, verified credentials, and gamified learning paths. TAM of $8B in peer learning segment.',
    fundingNeeds: 'Raising $500K for platform scaling, performance optimization, content creator acquisition, and geographic expansion. Investment will fuel growth from 50K to 250K users within 12 months while maintaining quality and community standards.',
    compatibilityInsights: [
      'Exceptional product-market fit with organic growth',
      'Strong network effects and retention metrics',
      'Scalable technology infrastructure',
      'Experienced EdTech leadership team',
      'Multiple monetization streams validated',
    ],
    recommendedFunders: ['3'],
    generatedAt: '2026-05-12',
  },
};
